/*!
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */

import {Type} from '@angular/core';

/**
 * Map of the previews components, values are functions which returns the promise of the component type, which will be displayed as preview in the ExampleViewer component.
 * Keys has to be equal to paths written down in the docs markdown files.
 */
export const PREVIEWS_COMPONENTS_MAP: Record<string, () => Promise<Type<unknown>>> = {
  ['adev/src/content/examples/angular-compiler-options/src/app/app.component.ts']: () => import('../../content/examples/angular-compiler-options/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/accessibility/src/app/app.component.ts']: () => import('../../content/examples/accessibility/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/accessibility/src/app/progress-bar.component.ts']: () => import('../../content/examples/accessibility/src/app/progress-bar.component').then(c => c.ExampleProgressbarComponent),
['adev/src/content/examples/drag-drop/src/axis-lock/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/axis-lock/app/app.component').then(c => c.CdkDragDropAxisLockExample),
['adev/src/content/examples/attribute-directives/src/app/app.component.1.ts']: () => import('../../content/examples/attribute-directives/src/app/app.component.1').then(c => c.AppComponent),
['adev/src/content/examples/attribute-directives/src/app/app.component.ts']: () => import('../../content/examples/attribute-directives/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/drag-drop/src/boundary/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/boundary/app/app.component').then(c => c.CdkDragDropBoundaryExample),
['adev/src/content/examples/built-in-directives/src/app/app.component.ts']: () => import('../../content/examples/built-in-directives/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/built-in-directives/src/app/item-switch.component.ts_StoutItemComponent']: () => import('../../content/examples/built-in-directives/src/app/item-switch.component').then(c => c.StoutItemComponent),
['adev/src/content/examples/built-in-directives/src/app/item-switch.component.ts_BestItemComponent']: () => import('../../content/examples/built-in-directives/src/app/item-switch.component').then(c => c.BestItemComponent),
['adev/src/content/examples/built-in-directives/src/app/item-switch.component.ts_DeviceItemComponent']: () => import('../../content/examples/built-in-directives/src/app/item-switch.component').then(c => c.DeviceItemComponent),
['adev/src/content/examples/built-in-directives/src/app/item-switch.component.ts_LostItemComponent']: () => import('../../content/examples/built-in-directives/src/app/item-switch.component').then(c => c.LostItemComponent),
['adev/src/content/examples/built-in-directives/src/app/item-switch.component.ts_UnknownItemComponent']: () => import('../../content/examples/built-in-directives/src/app/item-switch.component').then(c => c.UnknownItemComponent),
['adev/src/content/examples/drag-drop/src/connected-sorting-group/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/connected-sorting-group/app/app.component').then(c => c.CdkDragDropConnectedSortingGroupExample),
['adev/src/content/examples/drag-drop/src/copy-list/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/copy-list/app/app.component').then(c => c.CdkDragDropCopyListExample),
['adev/src/content/examples/drag-drop/src/connected-sorting/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/connected-sorting/app/app.component').then(c => c.CdkDragDropConnectedSortingExample),
['adev/src/content/examples/drag-drop/src/custom-handle/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/custom-handle/app/app.component').then(c => c.CdkDragDropHandleExample),
['adev/src/content/examples/drag-drop/src/custom-preview/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/custom-preview/app/app.component').then(c => c.CdkDragDropCustomPreviewExample),
['adev/src/content/examples/drag-drop/src/custom-placeholder/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/custom-placeholder/app/app.component').then(c => c.CdkDragDropCustomPlaceholderExample),
['adev/src/content/examples/drag-drop/src/delay-drag/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/delay-drag/app/app.component').then(c => c.CdkDragDropDelayExample),
['adev/src/content/examples/drag-drop/src/enter-predicate/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/enter-predicate/app/app.component').then(c => c.CdkDragDropEnterPredicateExample),
['adev/src/content/examples/drag-drop/src/free-drag-position/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/free-drag-position/app/app.component').then(c => c.CdkDragDropFreeDragPositionExample),
['adev/src/content/examples/drag-drop/src/horizontal-sorting/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/horizontal-sorting/app/app.component').then(c => c.CdkDragDropHorizontalSortingExample),
['adev/src/content/examples/drag-drop/src/overview/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/overview/app/app.component').then(c => c.CdkDragDropOverviewExample),
['adev/src/content/examples/drag-drop/src/mixed-sorting/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/mixed-sorting/app/app.component').then(c => c.CdkDragDropMixedSortingExample),
['adev/src/content/examples/drag-drop/src/disable-sorting/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/disable-sorting/app/app.component').then(c => c.CdkDragDropDisabledSortingExample),
['adev/src/content/examples/drag-drop/src/root-element/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/root-element/app/app.component').then(c => c.CdkDragDropRootElementExample),
['adev/src/content/examples/drag-drop/src/sorting/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/sorting/app/app.component').then(c => c.CdkDragDropSortingExample),
['adev/src/content/examples/dynamic-form/src/app/app.component.ts']: () => import('../../content/examples/dynamic-form/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/dynamic-form/src/app/dynamic-form-question.component.ts']: () => import('../../content/examples/dynamic-form/src/app/dynamic-form-question.component').then(c => c.DynamicFormQuestionComponent),
['adev/src/content/examples/dynamic-form/src/app/dynamic-form.component.ts']: () => import('../../content/examples/dynamic-form/src/app/dynamic-form.component').then(c => c.DynamicFormComponent),
['adev/src/content/examples/hello-world/src/app/app.component-old.ts']: () => import('../../content/examples/hello-world/src/app/app.component-old').then(c => c.HelloWorldComponent),
['adev/src/content/examples/hello-world/src/app/app.component.ts']: () => import('../../content/examples/hello-world/src/app/app.component').then(c => c.HelloWorldComponent),
['adev/src/content/examples/forms/src/app/app.component.ts']: () => import('../../content/examples/forms/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/forms-overview/src/app/app.component.ts']: () => import('../../content/examples/forms-overview/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/pipes/src/app/app.component.ts']: () => import('../../content/examples/pipes/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/pipes/src/app/birthday-formatting.component.ts']: () => import('../../content/examples/pipes/src/app/birthday-formatting.component').then(c => c.BirthdayFormattingComponent),
['adev/src/content/examples/pipes/src/app/birthday-pipe-chaining.component.ts']: () => import('../../content/examples/pipes/src/app/birthday-pipe-chaining.component').then(c => c.BirthdayPipeChainingComponent),
['adev/src/content/examples/pipes/src/app/birthday.component.ts']: () => import('../../content/examples/pipes/src/app/birthday.component').then(c => c.BirthdayComponent),
['adev/src/content/examples/pipes/src/app/flying-heroes.component.ts_FlyingHeroesComponent']: () => import('../../content/examples/pipes/src/app/flying-heroes.component').then(c => c.FlyingHeroesComponent),
['adev/src/content/examples/pipes/src/app/flying-heroes.component.ts_FlyingHeroesImpureComponent']: () => import('../../content/examples/pipes/src/app/flying-heroes.component').then(c => c.FlyingHeroesImpureComponent),
['adev/src/content/examples/pipes/src/app/hero-async-message.component.ts']: () => import('../../content/examples/pipes/src/app/hero-async-message.component').then(c => c.HeroAsyncMessageComponent),
['adev/src/content/examples/pipes/src/app/json-pipe.component.ts']: () => import('../../content/examples/pipes/src/app/json-pipe.component').then(c => c.JsonPipeComponent),
['adev/src/content/examples/pipes/src/app/power-booster.component.ts']: () => import('../../content/examples/pipes/src/app/power-booster.component').then(c => c.PowerBoosterComponent),
['adev/src/content/examples/pipes/src/app/precedence.component.ts']: () => import('../../content/examples/pipes/src/app/precedence.component').then(c => c.PrecedenceComponent),
['adev/src/content/examples/security/src/app/app.component.ts']: () => import('../../content/examples/security/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/security/src/app/bypass-security.component.ts']: () => import('../../content/examples/security/src/app/bypass-security.component').then(c => c.BypassSecurityComponent),
['adev/src/content/examples/security/src/app/inner-html-binding.component.ts']: () => import('../../content/examples/security/src/app/inner-html-binding.component').then(c => c.InnerHtmlBindingComponent),
['adev/src/content/examples/drag-drop/src/disable-drag/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/disable-drag/app/app.component').then(c => c.CdkDragDropDisabledExample),
['adev/src/content/examples/drag-drop/src/sort-predicate/app/app.component.ts']: () => import('../../content/examples/drag-drop/src/sort-predicate/app/app.component').then(c => c.CdkDragDropSortPredicateExample),
['adev/src/content/examples/animations/src/app/about.component.ts']: () => import('../../content/examples/animations/src/app/about.component').then(c => c.AboutComponent),
['adev/src/content/examples/animations/src/app/app.component.ts']: () => import('../../content/examples/animations/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/animations/src/app/hero-list-auto-page.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-auto-page.component').then(c => c.HeroListAutoCalcPageComponent),
['adev/src/content/examples/animations/src/app/hero-list-auto.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-auto.component').then(c => c.HeroListAutoComponent),
['adev/src/content/examples/animations/src/app/hero-list-enter-leave-page.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-enter-leave-page.component').then(c => c.HeroListEnterLeavePageComponent),
['adev/src/content/examples/animations/src/app/hero-list-enter-leave.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-enter-leave.component').then(c => c.HeroListEnterLeaveComponent),
['adev/src/content/examples/animations/src/app/hero-list-group-page.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-group-page.component').then(c => c.HeroListGroupPageComponent),
['adev/src/content/examples/animations/src/app/hero-list-groups.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-groups.component').then(c => c.HeroListGroupsComponent),
['adev/src/content/examples/animations/src/app/hero-list-page.component.ts']: () => import('../../content/examples/animations/src/app/hero-list-page.component').then(c => c.HeroListPageComponent),
['adev/src/content/examples/animations/src/app/home.component.ts']: () => import('../../content/examples/animations/src/app/home.component').then(c => c.HomeComponent),
['adev/src/content/examples/animations/src/app/insert-remove.component.ts']: () => import('../../content/examples/animations/src/app/insert-remove.component').then(c => c.InsertRemoveComponent),
['adev/src/content/examples/animations/src/app/open-close-page.component.ts']: () => import('../../content/examples/animations/src/app/open-close-page.component').then(c => c.OpenClosePageComponent),
['adev/src/content/examples/animations/src/app/open-close.component.1.ts']: () => import('../../content/examples/animations/src/app/open-close.component.1').then(c => c.OpenCloseKeyframeComponent),
['adev/src/content/examples/animations/src/app/open-close.component.2.ts']: () => import('../../content/examples/animations/src/app/open-close.component.2').then(c => c.OpenCloseBooleanComponent),
['adev/src/content/examples/animations/src/app/open-close.component.3.ts']: () => import('../../content/examples/animations/src/app/open-close.component.3').then(c => c.OpenCloseBooleanComponent),
['adev/src/content/examples/animations/src/app/open-close.component.4.ts']: () => import('../../content/examples/animations/src/app/open-close.component.4').then(c => c.OpenCloseChildComponent),
['adev/src/content/examples/animations/src/app/open-close.component.ts']: () => import('../../content/examples/animations/src/app/open-close.component').then(c => c.OpenCloseComponent),
['adev/src/content/examples/animations/src/app/querying.component.ts']: () => import('../../content/examples/animations/src/app/querying.component').then(c => c.QueryingComponent),
['adev/src/content/examples/animations/src/app/status-slider-page.component.ts']: () => import('../../content/examples/animations/src/app/status-slider-page.component').then(c => c.StatusSliderPageComponent),
['adev/src/content/examples/animations/src/app/status-slider.component.ts']: () => import('../../content/examples/animations/src/app/status-slider.component').then(c => c.StatusSliderComponent),
['adev/src/content/examples/animations/src/app/toggle-animations-page.component.ts']: () => import('../../content/examples/animations/src/app/toggle-animations-page.component').then(c => c.ToggleAnimationsPageComponent),
['adev/src/content/examples/structural-directives/src/app/app.component.ts']: () => import('../../content/examples/structural-directives/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/structural-directives/src/app/hero-switch.components.ts_HappyHeroComponent']: () => import('../../content/examples/structural-directives/src/app/hero-switch.components').then(c => c.HappyHeroComponent),
['adev/src/content/examples/structural-directives/src/app/hero-switch.components.ts_SadHeroComponent']: () => import('../../content/examples/structural-directives/src/app/hero-switch.components').then(c => c.SadHeroComponent),
['adev/src/content/examples/structural-directives/src/app/hero-switch.components.ts_ConfusedHeroComponent']: () => import('../../content/examples/structural-directives/src/app/hero-switch.components').then(c => c.ConfusedHeroComponent),
['adev/src/content/examples/structural-directives/src/app/hero-switch.components.ts_UnknownHeroComponent']: () => import('../../content/examples/structural-directives/src/app/hero-switch.components').then(c => c.UnknownHeroComponent),
['adev/src/content/examples/structural-directives/src/app/hero.component.ts']: () => import('../../content/examples/structural-directives/src/app/hero.component').then(c => c.HeroComponent),
['adev/src/content/examples/routing-with-urlmatcher/src/app/app.component.ts']: () => import('../../content/examples/routing-with-urlmatcher/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/router-tutorial/src/app/app.component.ts']: () => import('../../content/examples/router-tutorial/src/app/app.component').then(c => c.AppComponent),
['adev/src/content/examples/built-in-directives/src/app/item-detail/item-detail.component.ts']: () => import('../../content/examples/built-in-directives/src/app/item-detail/item-detail.component').then(c => c.ItemDetailComponent),
['adev/src/content/examples/animations/src/app/enter-and-leave/enter-binding.ts']: () => import('../../content/examples/animations/src/app/enter-and-leave/enter-binding').then(c => c.EnterBinding),
['adev/src/content/examples/animations/src/app/enter-and-leave/enter.ts']: () => import('../../content/examples/animations/src/app/enter-and-leave/enter').then(c => c.Enter),
['adev/src/content/examples/animations/src/app/enter-and-leave/leave-binding.ts']: () => import('../../content/examples/animations/src/app/enter-and-leave/leave-binding').then(c => c.LeaveBinding),
['adev/src/content/examples/animations/src/app/enter-and-leave/leave-event.ts']: () => import('../../content/examples/animations/src/app/enter-and-leave/leave-event').then(c => c.LeaveEvent),
['adev/src/content/examples/animations/src/app/enter-and-leave/leave.ts']: () => import('../../content/examples/animations/src/app/enter-and-leave/leave').then(c => c.Leave),
['adev/src/content/examples/animations/src/app/animations-package/auto-height.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/auto-height.component').then(c => c.AutoHeightComponent),
['adev/src/content/examples/animations/src/app/animations-package/increment-decrement.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/increment-decrement.component').then(c => c.IncrementDecrementComponent),
['adev/src/content/examples/animations/src/app/animations-package/insert-remove.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/insert-remove.component').then(c => c.InsertRemoveComponent),
['adev/src/content/examples/animations/src/app/animations-package/open-close.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/open-close.component').then(c => c.OpenCloseComponent),
['adev/src/content/examples/animations/src/app/animations-package/reorder.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/reorder.component').then(c => c.ReorderComponent),
['adev/src/content/examples/animations/src/app/animations-package/stagger.component.ts']: () => import('../../content/examples/animations/src/app/animations-package/stagger.component').then(c => c.StaggerComponent),
['adev/src/content/examples/animations/src/app/native-css/auto-height.component.ts']: () => import('../../content/examples/animations/src/app/native-css/auto-height.component').then(c => c.AutoHeightComponent),
['adev/src/content/examples/animations/src/app/native-css/increment-decrement.component.ts']: () => import('../../content/examples/animations/src/app/native-css/increment-decrement.component').then(c => c.IncrementDecrementComponent),
['adev/src/content/examples/animations/src/app/native-css/insert.component.ts']: () => import('../../content/examples/animations/src/app/native-css/insert.component').then(c => c.InsertComponent),
['adev/src/content/examples/animations/src/app/native-css/open-close.component.ts']: () => import('../../content/examples/animations/src/app/native-css/open-close.component').then(c => c.OpenCloseComponent),
['adev/src/content/examples/animations/src/app/native-css/remove.component.ts']: () => import('../../content/examples/animations/src/app/native-css/remove.component').then(c => c.RemoveComponent),
['adev/src/content/examples/animations/src/app/native-css/reorder.component.ts']: () => import('../../content/examples/animations/src/app/native-css/reorder.component').then(c => c.ReorderComponent),
['adev/src/content/examples/animations/src/app/native-css/stagger.component.ts']: () => import('../../content/examples/animations/src/app/native-css/stagger.component').then(c => c.StaggerComponent),
['adev/src/content/examples/routing-with-urlmatcher/src/app/profile/profile.component.ts']: () => import('../../content/examples/routing-with-urlmatcher/src/app/profile/profile.component').then(c => c.ProfileComponent),
['adev/src/content/examples/router-tutorial/src/app/heroes-list/heroes-list.component.ts']: () => import('../../content/examples/router-tutorial/src/app/heroes-list/heroes-list.component').then(c => c.HeroesListComponent),
['adev/src/content/examples/router-tutorial/src/app/crisis-list/crisis-list.component.ts']: () => import('../../content/examples/router-tutorial/src/app/crisis-list/crisis-list.component').then(c => c.CrisisListComponent),
['adev/src/content/examples/router-tutorial/src/app/page-not-found/page-not-found.component.ts']: () => import('../../content/examples/router-tutorial/src/app/page-not-found/page-not-found.component').then(c => c.PageNotFoundComponent),
['adev/src/content/examples/forms/src/app/actor-form/actor-form.component.ts']: () => import('../../content/examples/forms/src/app/actor-form/actor-form.component').then(c => c.ActorFormComponent),
['adev/src/content/examples/forms-overview/src/app/template/favorite-color/favorite-color.component.ts']: () => import('../../content/examples/forms-overview/src/app/template/favorite-color/favorite-color.component').then(c => c.FavoriteColorTemplateComponent),
['adev/src/content/examples/forms-overview/src/app/reactive/favorite-color/favorite-color.component.ts']: () => import('../../content/examples/forms-overview/src/app/reactive/favorite-color/favorite-color.component').then(c => c.FavoriteColorReactiveComponent),

};
